### ISSUE TITLE
Cannot run with my old database 

### ISSUE THREAD

**Issue by claeshg** [pytrainer/pytrainer#175] opened 2018-12-31 10:54 UTC
Last part of output after running a few times
sqlalchemy.exc.OperationalError: (pysqlite2.dbapi2.OperationalError) there is already another table or index with this name: migration_tmp [SQL: u'ALTER TABLE records RENAME TO migration_tmp']
 I was able to run it as root however

**Comment by viiru-** [comment] 2019-01-01 08:12
This database has apparently already had a migration attempted and failed. You should restore from the backup taken before the migration, retry and provide the error messages if a migration still fails. You could also check issue #140, the migration failure could be caused by the problems discussed there.

**Comment by claeshg** [comment] 2019-01-02 09:50
Restoring from backup I get:

.........  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (pysqlite2.dbapi2.IntegrityError) datatype mismatch [SQL: u'INSERT INTO laps SELECT * from migration_tmp']

and I didn't get any wiser from #140 eg id-lap seems to be in order

**Comment by claeshg** [comment] 2019-01-02 16:41
Now I've got it working, I first applied the column order fix in #140 and then got a plugin issue. Following the advice in #140 I removed the contents in the plugin folder. In the process for some reason the files in my gpx folder disappeared. Fortunately I had a backup.
I could also import new FIT-files from my Forerunner 25

**Comment by viiru-** [comment] 2019-01-05 09:15
Great that you got things working! I'll consider this to be a duplicate of #140, and close this issue.

**Closed by viiru-** 2019-01-05 09:15 UTC
