### ISSUE TITLE
no map displayed

### ISSUE THREAD

**Issue by bentrider** [pytrainer/pytrainer#118] opened 2018-02-19 22:19 UTC
Hello,
Very happy from several years with pytrainer, but I would signal an issue: with pytrainer 1.11.0, on mageia6, i cannot display any map
The log file with Google : 
`File "/usr/lib/python2.7/site-packages/pytrainer-1.11.0-py2.7.egg/pytrainer/gui/windowmain.py", line 1745, in on_radiobuttonMap_toggled
    self.parent.refreshMapView()
  File "/usr/lib/python2.7/site-packages/pytrainer-1.11.0-py2.7.egg/pytrainer/main.py", line 357, in refreshMapView
    self.windowmain.actualize_map(activity, full_screen)
  File "/usr/lib/python2.7/site-packages/pytrainer-1.11.0-py2.7.egg/pytrainer/gui/windowmain.py", line 1010, in actualize_map
    htmlfile = Googlemaps(data_path=self.data_path, waypoint=self.pytrainer_main.waypoint, pytrainer_main=self.parent).drawMap(activity, self.comboMapLineType.get_active())
NameError: global name 'Googlemaps' is not defined_`

or with OSM

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pytrainer-1.11.0-py2.7.egg/pytrainer/gui/windowmain.py", line 1749, in on_comboMapLineType_changed
    self.parent.refreshMapView()
  File "/usr/lib/python2.7/site-packages/pytrainer-1.11.0-py2.7.egg/pytrainer/main.py", line 357, in refreshMapView
    self.windowmain.actualize_map(activity, full_screen)
  File "/usr/lib/python2.7/site-packages/pytrainer-1.11.0-py2.7.egg/pytrainer/gui/windowmain.py", line 1006, in actualize_map
    htmlfile = Osm(data_path=self.data_path, waypoint=self.pytrainer_main.waypoint, pytrainer_main=self.parent).drawMap(activity, self.comboMapLineType.get_active())
NameError: global name 'Osm' is not defined

any solution.
Thanks
Olivier

**Comment by viiru-** [comment] 2018-02-20 19:21
This is a duplicate of #103, which has been fixed in git. I'm hoping to release version 1.12.0 which includes the fix soon.

**Closed by viiru-** 2018-02-20 19:21 UTC

**Comment by bentrider** [comment] 2018-02-21 12:06
many thanks, working now with Google maps, but some  errors in openlayers.js for osmunexpected token '@7 can't find variable :Openlayersdepends on openstreetmap, isn't it ?Olivier-------- Message original --------Objet : Re: [pytrainer/pytrainer] no map displayed (#118)De : Arto Jantunen À : pytrainer/pytrainer Cc : bentrider ,Author This is a duplicate of #103, which has been fixed in git. I'm hoping to release version 1.12.0 which includes the fix soon.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pytrainer/pytrainer","title":"pytrainer/pytrainer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pytrainer/pytrainer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@viiru- in #118: This is a duplicate of #103, which has been fixed in git. I'm hoping to release version 1.12.0 which includes the fix soon."}],"action":{"name":"View Issue","url":"https://github.com/pytrainer/pytrainer/issues/118#issuecomment-367088942"}}}

**Comment by viiru-** [comment] 2018-02-24 06:36
I think that is caused by OSM removing support for deprecated clients such as python-webkit.
